In [1]:
import pandas as pd

In [2]:
zhvi = pd.read_csv("../data/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv")

In [3]:
zhvi.shape

(895, 323)

In [4]:
zhvi.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       '2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30', '2000-05-31',
       ...
       '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31', '2026-01-31',
       '2026-02-28', '2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30'],
      dtype='str', length=323)

In [5]:
zhvi.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30
0,102001,0,United States,country,NaN,125206.997378,125427.276624,125700.455324,126286.370014,126960.687576,...,369475.972328,369920.427655,370612.174008,371421.454541,372193.561275,372924.337793,373426.328497,373507.545378,373242.049037,372995.192537
1,394913,1,"New York, NY",msa,NY,222017.778856,222961.229149,223913.417492,225842.919527,227840.985703,...,709628.293851,712004.813811,715405.757117,718885.828185,722003.180517,725638.840804,729493.235819,731943.853454,733495.479875,735003.128702
2,753899,2,"Los Angeles, CA",msa,CA,225885.767913,226726.349571,227845.996323,230073.717243,232510.145535,...,959296.407537,961759.656310,965141.641357,969178.618533,971757.837797,973013.669103,972673.281150,971019.676130,969535.332329,968028.188948
3,394463,3,"Chicago, IL",msa,IL,159015.886004,159163.088391,159443.437931,160140.877915,160979.814326,...,347637.905227,348990.073801,350593.897618,352389.170193,354068.029351,355878.069464,357334.820796,358370.099664,359004.083536,359887.600103
4,394514,4,"Dallas, TX",msa,TX,131742.629314,131801.307941,131868.765030,132043.944005,132274.912687,...,373911.443083,373551.625958,373279.474416,373054.749618,372607.263853,372013.540892,370924.767470,369570.718315,367967.779219,366701.488281

In [6]:
zhvi[zhvi["RegionName"].str.contains("Cleveland")]

,RegionID,SizeRank,RegionName,RegionType,StateName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,...,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30
34,394475,35,"Cleveland, OH",msa,OH,121808.671097,121987.283217,122169.789043,122550.593574,123137.865382,...,248500.521318,249230.013552,250186.705347,251222.324056,252245.403853,253216.918528,254053.454974,254739.498734,255166.763725,255598.498594
324,394474,334,"Cleveland, TN",msa,TN,102604.340224,102715.652132,102801.593587,103025.317027,103304.614007,...,309780.942149,310871.193306,312340.884392,313555.864117,314610.932547,315399.638117,316132.533266,316680.984623,316905.681601,317005.001803
778,394473,806,"Cleveland, MS",msa,MS,NaN,NaN,NaN,NaN,NaN,...,125120.933871,124253.534329,123364.404121,122580.516612,122183.180126,122476.172653,123564.773215,123677.409690,122714.564186,120737.681522

In [7]:
zhvi[zhvi["RegionName"].str.contains("Columbus|Cincinnati|Indianapolis|Pittsburgh|Detroit|New York")]["RegionName"]

1          New York, NY
14          Detroit, MI
27       Pittsburgh, PA
28       Cincinnati, OH
32         Columbus, OH
33     Indianapolis, IN
155        Columbus, GA
432        Columbus, IN
526        Columbus, MS
755        Columbus, NE
Name: RegionName, dtype: str

In [8]:
metros = [
    "Cleveland, OH",
    "Columbus, OH",
    "Cincinnati, OH",
    "Indianapolis, IN",
    "Pittsburgh, PA",
    "Detroit, MI",
    "New York, NY"
]

In [9]:
zhvi_metros = zhvi[zhvi["RegionName"].isin(metros)]
zhvi_metros.shape

(7, 323)

In [10]:
zhvi_long = zhvi_metros.melt(
    id_vars=["RegionID", "SizeRank", "RegionName", "RegionType", "StateName"],
    var_name="date",
    value_name="home_value"
)
zhvi_long.shape

(2226, 7)

In [11]:
zhvi_long.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,date,home_value
0,394913,1,"New York, NY",msa,NY,2000-01-31,222017.778856
1,394532,14,"Detroit, MI",msa,MI,2000-01-31,127088.584728
2,394982,27,"Pittsburgh, PA",msa,PA,2000-01-31,91353.664520
3,394466,28,"Cincinnati, OH",msa,OH,2000-01-31,131773.477497
4,394492,32,"Columbus, OH",msa,OH,2000-01-31,130280.167512

In [12]:
zhvi_long.dtypes

RegionID        int64
SizeRank        int64
RegionName        str
RegionType        str
StateName         str
date              str
home_value    float64
dtype: object

In [13]:
zhvi_long["date"] = pd.to_datetime(zhvi_long["date"])
zhvi_long.dtypes

RegionID               int64
SizeRank               int64
RegionName               str
RegionType               str
StateName                str
date          datetime64[us]
home_value           float64
dtype: object

In [14]:
zhvi_long = zhvi_long[zhvi_long["date"] >= "2015-01-01"]
zhvi_long.shape

(966, 7)